⠀

diff --git a/usr/local/discourse/templates/postgres.template.yml b/usr/local/discourse/templates/postgres.template.yml
--- a/usr/local/discourse/templates/postgres.template.yml
+++ b/usr/local/discourse/templates/postgres.template.yml
@@ -1,6 +1,7 @@
 # 2024-05-30
 # "[Discourse] «Your local changes to the following files would be overwritten by merge:
 # templates/postgres.template.yml» on `./launcher rebuild`": https://github.com/dmitrii-fediuk/5.9.188.84/issues/61
+base_image: discourse/base:2.0.20251003-1437
 params:
   db_synchronous_commit: "off"
   # 2024-05-31 I moved `db_shared_buffers` and `db_work_mem` to `templates-my`
@@ -17,10 +18,6 @@ hooks:
        filename: /etc/service/unicorn/run
        from: "# postgres"
        to: |
-         if [ -f /root/install_postgres ]; then
-           /root/install_postgres
-           rm /root/install_postgres
-         fi
          sv start postgres || exit 1
 
 run:
@@ -30,7 +27,16 @@ run:
      contents: |
         #!/bin/sh
         exec 2>&1
-        HOME=/var/lib/postgresql USER=postgres exec thpoff chpst -u postgres:postgres:ssl-cert -U postgres:postgres:ssl-cert /usr/lib/postgresql/13/bin/postmaster -D /etc/postgresql/13/main
+        if [ -f /root/install_postgres ]; then
+          /root/install_postgres
+          rm /root/install_postgres
+        fi
+        if [ "$CREATE_DB_ON_BOOT" = "1" ]; then
+          sudo -E -u postgres /usr/lib/postgresql/15/bin/pg_ctl -D /etc/postgresql/15/main -o "-c listen_addresses='' -p 5432" -w start
+          /usr/local/bin/create_db
+          sudo -E -u postgres /usr/lib/postgresql/15/bin/pg_ctl -D /etc/postgresql/15/main -m fast -w stop
+        fi
+        HOME=/var/lib/postgresql USER=postgres exec thpoff chpst -u postgres:postgres:ssl-cert -U postgres:postgres:ssl-cert /usr/lib/postgresql/15/bin/postmaster -D /etc/postgresql/15/main
 
   - file:
      path: /etc/service/postgres/log/run
@@ -52,27 +58,36 @@ run:
       chmod: "+x"
       contents: |
         #!/bin/bash
-        locale-gen $LANG && update-locale
+        run_upgrade_postgres() {
+          if [ -f /root/upgrade_postgres ]; then
+            unset RETCODE
+            /root/upgrade_postgres || RETCODE=$?
+            [ -z "${RETCODE}" ] && rm /root/upgrade_postgres || exit $RETCODE
+          fi
+          exit 0
+        }
+        sed -i "s/^# $LANG/$LANG/" /etc/locale.gen
+        locale-gen && update-locale
         mkdir -p /shared/postgres_run
         chown postgres:postgres /shared/postgres_run
         chmod 775 /shared/postgres_run
         rm -fr /var/run/postgresql
         ln -s /shared/postgres_run /var/run/postgresql
         if [ -e /shared/postgres_run/.s.PGSQL.5432 ]; then
-          socat /dev/null UNIX-CONNECT:/shared/postgres_run/.s.PGSQL.5432 || exit 0 && echo postgres already running stop container ; exit 1
+          socat /dev/null UNIX-CONNECT:/shared/postgres_run/.s.PGSQL.5432 || run_upgrade_postgres && echo postgres already running stop container ; exit 1
         fi
         rm -fr /shared/postgres_run/.s*
         rm -fr /shared/postgres_run/*.pid
-        mkdir -p /shared/postgres_run/13-main.pg_stat_tmp
-        chown postgres:postgres /shared/postgres_run/13-main.pg_stat_tmp
-        chown -R root /var/lib/postgresql/13/main
-        [ ! -e /shared/postgres_data ] && install -d -m 0755 -o postgres -g postgres /shared/postgres_data && sudo -E -u postgres /usr/lib/postgresql/13/bin/initdb -D /shared/postgres_data || exit 0
-        chown -R postgres:postgres /shared/postgres_data
-        chown -R postgres:postgres /var/run/postgresql
-        if [ -f /root/upgrade_postgres ]; then
-          /root/upgrade_postgres
-          rm /root/upgrade_postgres
+        mkdir -p /shared/postgres_run/15-main.pg_stat_tmp
+        chown postgres:postgres /shared/postgres_run/15-main.pg_stat_tmp
+        chown -R root /var/lib/postgresql/15/main
+        if [ ! -e /shared/postgres_data ]; then
+          install -d -m 0755 -o postgres -g postgres /shared/postgres_data
+          sudo -E -u postgres /usr/lib/postgresql/15/bin/initdb -D /shared/postgres_data
         fi
+        find /shared/postgres_data \! -user postgres -exec chown postgres '{}' +
+        find /var/run/postgresql \! -user postgres -exec chown postgres '{}' +
+        run_upgrade_postgres
         # Necessary to enable backups
         install -d -m 0755 -o postgres -g postgres /shared/postgres_backup
 
@@ -83,17 +98,22 @@ run:
        #!/bin/bash
        PG_MAJOR_OLD=`cat /shared/postgres_data/PG_VERSION`
 
-       if [ ! "13" = "$PG_MAJOR_OLD" ]; then
-         echo Upgrading PostgreSQL from version ${PG_MAJOR_OLD} to 13
+       if [ ! "15" = "$PG_MAJOR_OLD" ]; then
+         echo Upgrading PostgreSQL from version ${PG_MAJOR_OLD} to 15
          free_disk=$(df -P -B1 /shared | tail -n 1 | awk '{print $4}')
          required=$(($(du -sb /shared/postgres_data | awk '{print $1}') * 2))
 
          if [ "$free_disk" -lt "$required" ]; then
-          echo "WARNING: Upgrading PostgreSQL would require an additional $(numfmt --to=si $(($required - $free_disk))) of disk space"
-          echo "Please free up some space, or expand your disk, before continuing."
-          echo ''
-          echo 'To avoid upgrading change "templates/postgres.template.yml" TO "templates/postgres.12.template.yml" in containers/app.yml'
-          exit 1
+           echo
+           echo -------------------------------------------------------------------------------------
+           echo "WARNING: Upgrading PostgreSQL would require an additional $(numfmt --to=si $(($required - $free_disk))) of disk space"
+           echo "Please free up some space, or expand your disk, before continuing."
+           echo
+           echo 'To avoid upgrading change "templates/postgres.template.yml" TO "templates/postgres.13.template.yml" in containers/app.yml'
+           echo
+           echo 'You can run "./launcher start app" to restart your app in the meanwhile.'
+           echo -------------------------------------------------------------------------------------
+           exit 1
          fi
 
          if [ -d /shared/postgres_data_old ]; then
@@ -101,10 +121,11 @@ run:
          fi
 
          rm -fr /shared/postgres_data_new
-         install -d -m 0755 -o postgres -g postgres /shared/postgres_data_new && sudo -u postgres /usr/lib/postgresql/13/bin/initdb -D /shared/postgres_data_new || exit 0
+         install -d -m 0755 -o postgres -g postgres /shared/postgres_data_new && sudo -u postgres /usr/lib/postgresql/15/bin/initdb -D /shared/postgres_data_new || exit 0
          apt-get update
-         apt-get install -y postgresql-${PG_MAJOR_OLD}
-         chown -R postgres:postgres /var/lib/postgresql/13
+         apt-get install -y postgresql-${PG_MAJOR_OLD} postgresql-${PG_MAJOR_OLD}-pgvector
+         pg_createcluster -u postgres --no-status ${PG_MAJOR_OLD} main
+         chown -R postgres:postgres /var/lib/postgresql/15
          /etc/init.d/postgresql stop
          rm -fr /shared/postgres_data/postmaster.pid
          cd ~postgres
@@ -112,21 +133,23 @@ run:
          echo  >> /shared/postgres_data/postgresql.conf
          echo "data_directory = '/shared/postgres_data'" >> /shared/postgres_data/postgresql.conf
          SUCCESS=true
-         sudo -u postgres /usr/lib/postgresql/13/bin/pg_upgrade -d /shared/postgres_data -D /shared/postgres_data_new -b /usr/lib/postgresql/${PG_MAJOR_OLD}/bin -B /usr/lib/postgresql/13/bin || SUCCESS=false
+         sudo -u postgres /usr/lib/postgresql/15/bin/pg_upgrade -d /shared/postgres_data -D /shared/postgres_data_new -b /usr/lib/postgresql/${PG_MAJOR_OLD}/bin -B /usr/lib/postgresql/15/bin || SUCCESS=false
 
          if [[ "$SUCCESS" == 'false' ]]; then
            echo -------------------------------------------------------------------------------------
            echo UPGRADE OF POSTGRES FAILED
            echo
-           echo Please visit https://meta.discourse.org/t/postgresql-13-update/172563 for support.
+           echo Please visit https://meta.discourse.org/t/postgresql-15-update/349515 for support.
            echo
            echo You can run "./launcher start app" to restart your app in the meanwhile
-           echo
+           echo -------------------------------------------------------------------------------------
            exit 1
          fi
 
-         mv /shared/postgres_data /shared/postgres_data_old
-         mv /shared/postgres_data_new /shared/postgres_data
+         mkdir /shared/postgres_data_old
+         mv /shared/postgres_data/* /shared/postgres_data_old
+         mv /shared/postgres_data_new/* /shared/postgres_data
+         rmdir /shared/postgres_data_new
 
          echo -------------------------------------------------------------------------------------
          echo UPGRADE OF POSTGRES COMPLETE
@@ -142,69 +165,69 @@ run:
        fi
 
   - replace:
-      filename: "/etc/postgresql/13/main/postgresql.conf"
-      from: "data_directory = '/var/lib/postgresql/13/main'"
+      filename: "/etc/postgresql/15/main/postgresql.conf"
+      from: "data_directory = '/var/lib/postgresql/15/main'"
       to: "data_directory = '/shared/postgres_data'"
 
   # listen on all interfaces
   - replace:
-      filename: "/etc/postgresql/13/main/postgresql.conf"
+      filename: "/etc/postgresql/15/main/postgresql.conf"
       from: /#?listen_addresses *=.*/
       to: "listen_addresses = '*'"
 
   # sync commit off is faster and less spiky, also marginally less safe
   - replace:
-      filename: "/etc/postgresql/13/main/postgresql.conf"
+      filename: "/etc/postgresql/15/main/postgresql.conf"
       from: /#?synchronous_commit *=.*/
       to: "synchronous_commit = $db_synchronous_commit"
 
   # default is 128MB which is way too small
   - replace:
-      filename: "/etc/postgresql/13/main/postgresql.conf"
+      filename: "/etc/postgresql/15/main/postgresql.conf"
       from: /#?shared_buffers *=.*/
       to: "shared_buffers = $db_shared_buffers"
 
   # default is 1MB which is too small
   - replace:
-      filename: "/etc/postgresql/13/main/postgresql.conf"
+      filename: "/etc/postgresql/15/main/postgresql.conf"
       from: /#?work_mem *=.*/
       to: "work_mem = $db_work_mem"
 
   # allow for other
   - replace:
-      filename: "/etc/postgresql/13/main/postgresql.conf"
+      filename: "/etc/postgresql/15/main/postgresql.conf"
       from: /#?default_text_search_config *=.*/
       to: "default_text_search_config = '$db_default_text_search_config'"
 
   - replace:
-      filename: "/etc/postgresql/13/main/postgresql.conf"
+      filename: "/etc/postgresql/15/main/postgresql.conf"
       from: /#?checkpoint_segments *=.*/
       to: "checkpoint_segments = $db_checkpoint_segments"
 
   - replace:
-      filename: "/etc/postgresql/13/main/postgresql.conf"
+      filename: "/etc/postgresql/15/main/postgresql.conf"
       from: /#?logging_collector *=.*/
       to: "logging_collector = $db_logging_collector"
 
   - replace:
-      filename: "/etc/postgresql/13/main/postgresql.conf"
+      filename: "/etc/postgresql/15/main/postgresql.conf"
       from: /#?log_min_duration_statement *=.*/
       to: "log_min_duration_statement = $db_log_min_duration_statement"
 
   - replace:
-      filename: "/etc/postgresql/13/main/pg_hba.conf"
+      filename: "/etc/postgresql/15/main/pg_hba.conf"
       from: /^#local +replication +postgres +peer$/
       to: "local replication postgres  peer"
 
-  # allow all to connect in with md5 auth
+  # allow all to connect in with md5/scram auth
   - replace:
-      filename: "/etc/postgresql/13/main/pg_hba.conf"
+      filename: "/etc/postgresql/15/main/pg_hba.conf"
       from: /^host.*all.*all.*127.*$/
       to: "host all all 0.0.0.0/0 md5"
 
-  # allow all to connect in with md5 auth (IPv6)
+  # allow all to connect in with md5/scram auth (IPv6)
   - replace:
-      filename: "/etc/postgresql/13/main/pg_hba.conf"
+      filename: "/etc/postgresql/15/main/pg_hba.conf"
       from: /^host.*all.*all.*::1\/128.*$/
       to: "host all all ::/0 md5"
 
@@ -222,7 +245,7 @@ run:
       background: true
       # use fast shutdown for pg
       stop_signal: INT
-      cmd: HOME=/var/lib/postgresql USER=postgres exec chpst -u postgres:postgres:ssl-cert -U postgres:postgres:ssl-cert /usr/lib/postgresql/13/bin/postmaster -D /etc/postgresql/13/main
+      cmd: HOME=/var/lib/postgresql USER=postgres exec chpst -u postgres:postgres:ssl-cert -U postgres:postgres:ssl-cert /usr/lib/postgresql/15/bin/postmaster -D /etc/postgresql/15/main
 
   - file:
       path: /usr/local/bin/create_db
@@ -242,6 +265,9 @@ run:
         su postgres -c 'psql $db_name -c "create extension if not exists vector;"'
         su postgres -c 'psql $db_name -c "alter extension vector update;"' || true
         sudo -u postgres psql $db_name <<< "update pg_database set encoding = pg_char_to_encoding('UTF8') where datname = '$db_name' AND encoding = pg_char_to_encoding('SQL_ASCII');" || true
+        if [ ! -z "$DISCOURSE_DB_PASSWORD" ]; then
+          echo "alter user $db_user with password '$DISCOURSE_DB_PASSWORD';" | su - postgres -c 'psql $db_name'
+        fi
 
   - file:
      path: /var/lib/postgresql/take-database-backup
diff --git a/usr/local/discourse/templates/web.template.yml b/usr/local/discourse/templates/web.template.yml
--- a/usr/local/discourse/templates/web.template.yml
+++ b/usr/local/discourse/templates/web.template.yml
@@ -1,3 +1,4 @@
+base_image: discourse/base:2.0.20251003-1437
 env:
   # You can have redis on a different box
   RAILS_ENV: 'production'
@@ -12,7 +13,6 @@ env:
   DISCOURSE_DB_HOST:
   DISCOURSE_DB_PORT:
 
-
 params:
   # 2024-05-31 I moved `version` to `templates-my/1.yml`
   home: /var/www/discourse
@@ -24,7 +24,7 @@ run:
   - exec:
       tag: precompile
       cmd:
-        - /usr/local/bin/ruby -e 'if ENV["DISCOURSE_SMTP_ADDRESS"] == "smtp.example.com"; puts "Aborting! Mail is not configured!"; exit 1; end'
+        - /usr/local/bin/ruby -e 'if (ENV["DISCOURSE_SMTP_ADDRESS"] == "smtp.example.com" && ENV["DISCOURSE_SKIP_EMAIL_SETUP"] != "1"); puts "Aborting! Mail is not configured!"; exit 1; end'
         - /usr/local/bin/ruby -e 'if ENV["DISCOURSE_HOSTNAME"] == "discourse.example.com"; puts "Aborting! Domain is not configured!"; exit 1; end'
         - /usr/local/bin/ruby -e 'if (ENV["DISCOURSE_CDN_URL"] || "")[0..1] == "//"; puts "Aborting! CDN must have a protocol specified. Once fixed you should rebake your posts now to correct all posts."; exit 1; end'
   # TODO: move to base image (anacron can not be fired up using rc.d)
@@ -45,7 +45,7 @@ run:
         conf=/var/www/discourse/config/discourse.conf
 
         # find DISCOURSE_ env vars, strip the leader, lowercase the key
-        /usr/local/bin/ruby -e 'ENV.each{|k,v| puts "#{$1.downcase} = '\''#{v}'\''" if k =~ /^DISCOURSE_(.*)/}' > $conf
+        /usr/local/bin/ruby -e 'ENV.each{|k,v| puts "#{$1.downcase} = '\''#{v}'\''" if k =~ /^DISCOURSE_(.*)/}' | install -m 600 -o discourse /dev/stdin ${conf}
 
   - file:
      path: /etc/service/unicorn/run
@@ -57,12 +57,16 @@ run:
         # postgres
         cd $home
         chown -R discourse:www-data /shared/log/rails
+        # before precompile
         if [[ -z "$PRECOMPILE_ON_BOOT" ]]; then
           PRECOMPILE_ON_BOOT=1
         fi
-        if [ -f /usr/local/bin/create_db ] && [ "$CREATE_DB_ON_BOOT" = "1" ]; then /usr/local/bin/create_db; fi;
-        if [ "$MIGRATE_ON_BOOT" = "1" ]; then su discourse -c 'bundle exec rake db:migrate'; fi
-        if [ "$PRECOMPILE_ON_BOOT" = "1" ]; then SKIP_EMBER_CLI_COMPILE=1 su discourse -c 'bundle exec rake assets:precompile'; fi
+        if [ "$MIGRATE_ON_BOOT" = "1" ]; then
+          su discourse -c 'bundle exec rake db:migrate' || exit 1
+        fi
+        if [ "$PRECOMPILE_ON_BOOT" = "1" ]; then
+          SKIP_EMBER_CLI_COMPILE=1 su discourse -c 'bundle exec rake assets:precompile' || exit 1
+        fi
         LD_PRELOAD=$RUBY_ALLOCATOR HOME=/home/discourse USER=discourse exec thpoff chpst -u discourse:www-data -U discourse:www-data bundle exec config/unicorn_launcher -E production -c config/unicorn.conf.rb
 
   - file:
@@ -91,23 +95,11 @@ run:
       cd: $home
       hook: code
       cmd:
-        - sudo -H -E -u discourse git reset --hard
         - sudo -H -E -u discourse git clean -f
-        # TODO Remove the special handling of shallow clones when everyone uses images without that clone type
         - |-
           sudo -H -E -u discourse bash -c '
             set -o errexit
-            if [ $(git rev-parse --is-shallow-repository) == "true" ]; then
-                git remote set-branches --add origin main
-                git remote set-branches origin $version
-                git fetch --depth 1 origin $version
-            else
-                git fetch --tags --prune-tags --prune --force origin
-            fi
-          '
-        - |-
-          sudo -H -E -u discourse bash -c '
-            set -o errexit
+            git fetch --tags --prune-tags --prune --force origin
             if [[ $(git symbolic-ref --short HEAD) == $version ]] ; then
                 git pull
             else
@@ -137,32 +129,48 @@ run:
         - "rm /etc/nginx/sites-enabled/default"
         - "mkdir -p /var/nginx/cache"
 
+        # Stop building the container if the Nginx outlets are missing
+        - "grep -q 'outlets/before-server' /etc/nginx/conf.d/discourse.conf || ( >&2 echo 'The \"before-server\" Nginx outlet is missing. This version of discourse_docker is not compatible with the chosen Discourse version.' ; exit 1 )"
+        - "grep -q 'outlets/server' /etc/nginx/conf.d/discourse.conf || ( >&2 echo 'The \"server\" Nginx outlet is missing. This version of discourse_docker is not compatible with the chosen Discourse version.' ; exit 1 )"
+        - "grep -q 'outlets/discourse' /etc/nginx/conf.d/discourse.conf || ( >&2 echo 'The \"discourse\" Nginx outlet is missing. This version of discourse_docker is not compatible with the chosen Discourse version.' ; exit 1 )"
+
+        # Create placeholders for the Nginx outlets
+        - "mkdir -p /etc/nginx/conf.d/outlets/before-server"
+        - "touch /etc/nginx/conf.d/outlets/before-server/20-redirect-http-to-https.conf"
+        - "touch /etc/nginx/conf.d/outlets/before-server/30-ratelimited.conf"
+        - "mkdir -p /etc/nginx/conf.d/outlets/server"
+        - "touch /etc/nginx/conf.d/outlets/server/10-http.conf"
+        - "touch /etc/nginx/conf.d/outlets/server/20-https.conf"
+        - "touch /etc/nginx/conf.d/outlets/server/30-offline-page.conf"
+        - "mkdir -p /etc/nginx/conf.d/outlets/discourse"
+        - "touch /etc/nginx/conf.d/outlets/discourse/20-https.conf"
+        - "touch /etc/nginx/conf.d/outlets/discourse/30-ratelimited.conf"
+
   - replace:
       filename: /etc/nginx/nginx.conf
       from: pid /run/nginx.pid;
       to: daemon off;
 
   - replace:
-      filename: "/etc/nginx/conf.d/discourse.conf"
-      from: /upstream[^\}]+\}/m
-      to: "upstream discourse {
-        server 127.0.0.1:3000;
-      }"
-
-  - replace:
-      filename: "/etc/nginx/conf.d/discourse.conf"
-      from: /server_name.+$/
-      to: server_name _ ;
+      filename: "/etc/nginx/nginx.conf"
+      from: /worker_connections.+$/
+      to: worker_connections $nginx_worker_connections;
 
   - replace:
       filename: "/etc/nginx/conf.d/discourse.conf"
       from: /client_max_body_size.+$/
-      to: client_max_body_size $upload_size ;
+      to: client_max_body_size $upload_size;
 
-  - replace:
-      filename: "/etc/nginx/nginx.conf"
-      from: /worker_connections.+$/
-      to: worker_connections $nginx_worker_connections ;
+  - exec:
+      cmd:
+        # Move `listen 80` to an outlet
+        - sed -i 's#listen 80;##g' /etc/nginx/conf.d/discourse.conf
+        - |-
+          if [ -f "/proc/net/if_inet6" ]; then
+            echo "listen 80;\nlisten [::]:80;" > /etc/nginx/conf.d/outlets/server/10-http.conf
+          else
+            echo "listen 80;" > /etc/nginx/conf.d/outlets/server/10-http.conf
+          fi
 
   - exec:
       cmd: echo "done configuring web"
@@ -188,7 +196,7 @@ run:
             fi
             su discourse -c 'yarn install --frozen-lockfile && yarn cache clean'
           else
-            su discourse -c 'CI=1 pnpm install --frozen-lockfile'
+            su discourse -c 'CI=1 pnpm install --frozen-lockfile && pnpm prune'
           fi
 
   - exec:
@@ -196,6 +204,9 @@ run:
       hook: bundle_exec
       cmd:
         - su discourse -c 'bundle install --jobs $(($(nproc) - 1)) --retry 3'
+        - su discourse -c 'bundle clean'
+        - su discourse -c 'find /var/www/discourse/vendor/bundle -name cache -not -path "*/gems/*" -type d -exec rm -rf {} +'
+        - su discourse -c 'find /var/www/discourse/vendor/bundle -name tmp -type d -exec rm -rf {} +'
 
   - exec:
       cd: $home
@@ -222,10 +233,11 @@ run:
       hook: assets_precompile
       cmd:
         - su discourse -c 'SKIP_EMBER_CLI_COMPILE=1 bundle exec rake themes:update assets:precompile'
+
   - replace:
       tag: precompile
       filename: /etc/service/unicorn/run
-      from: PRECOMPILE_ON_BOOT=1
+      from: "# before precompile"
       to: "PRECOMPILE_ON_BOOT=0"
 
   - file:
@@ -240,13 +252,7 @@ run:
      chmod: +x
      contents: |
        #!/bin/bash
-       # If they requested a console, load pry instead
-       if [ "$*" == "c" -o "$*" == "console" ]
-       then
-        (cd /var/www/discourse && RAILS_ENV=production sudo -H -E -u discourse bundle exec pry -r ./config/environment)
-       else
-        (cd /var/www/discourse && RAILS_ENV=production sudo -H -E -u discourse bundle exec script/rails "$@")
-       fi
+       (cd /var/www/discourse && RAILS_ENV=production sudo -H -E -u discourse bundle exec script/rails "$@")
 
   - file:
      path: /usr/local/bin/rake
@@ -290,9 +296,7 @@ run:
                 delaycompress
                 compress
                 sharedscripts
-                postrotate
-                sv 1 unicorn
-                endscript
+                copytruncate
         }
 
   - file:
